[package]
name = "testkit-examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
testkit-core = { path = "../testkit-core" }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

[[example]]
name = "fluent_api"
path = "fluent_api.rs"
