[package]
name = "testkit-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { version = "0.1.40", features = [], optional = true }
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
], optional = true }


[features]
default = ["tracing"]
tracing = ["dep:tracing", "dep:tracing-subscriber"]
