[package]
name = "testkit-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive", "env"] }
testkit-mysql = { path = "../testkit-mysql" }
testkit-postgres = { path = "../testkit-postgres" }

[[bin]]
name = "testkit"
path = "src/main.rs"
